name: Build and Deploy Multi-Env

on:
  push:
    branches:
      - develop
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TAG=dev-${{ github.run_number }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "ENV=qa" >> $GITHUB_ENV
            echo "TAG=qa-${{ github.run_number }}" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${TAG} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${ENV}-latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${TAG}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${ENV}-latest

      - name: Update GitOps Repo
        run: |
          git clone https://github.com/sohampa/multicluster_deployment_argocd.git
          cd multicluster_deployment_argocd/manifest/${ENV}
      
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${TAG}|g" spring-boot-app-stable-deployment.yaml
      
          git config user.email "ci@github.com"
          git config user.name "github-actions"
          git add spring-boot-app-stable-deployment.yaml
          git commit -m "Update ${ENV} image to ${TAG}"
          git push
